const sections = {
    0: {
        id: 0, 
        name: 'root',
        childIds: [1, 2, 3],
        required: false,
        type: 'root',
        innerText: '',
    },
    1: {
        id: 1,
        name: 'general',
        childIds: [4, 5, 6, 7],
        required: false,
        type: 'container',
        innerText: '',
    },
    2: {
        id: 2,
        name: 'education',
        childIds: [8, 9, 10, 11, 12],
        required: false,
        type: 'container',
        innerText: '',
    },
    3: {
        id: 3,
        name: 'experience',
        childIds: [13, 14, 15],
        required: false,
        type: 'experience',
        innerText: '',
    },
    4: {
        id: 4,
        name: 'first-name',
        childIds: [],
        required: true,
        type: 'text',
        innerText: '',
    },
    5: {
        id: 5,
        name: 'last-name',
        childIds: [],
        required: true,
        type: 'text',
        innerText: '',
    },
    6: {
        id: 6,
        name: 'email',
        childIds: [],
        required: true,
        type: 'email',
        innerText: '',
    },
    7: {
        id: 7,
        name: 'phone',
        childIds: [],
        required: true,
        type: 'tel',
        innerText: '',
    },
    8: {
        id: 8,
        name: 'institution',
        childIds: [],
        required: true,
        type: 'text',
        innerText: '',
    },
    9: {
        id: 9,
        name: 'start-year',
        childIds: [],
        required: true,
        type: 'date',
        innerText: '',
    },
    10: {
        id: 10,
        name: 'end-year',
        childIds: [],
        required: true,
        type: 'date',
        innerText: '',
    },
    11: {
        id: 11,
        name: 'degree',
        childIds: [],
        required: true,
        type: 'text',
        innerText: '',
    },
    12: {
        id: 12,
        name: 'gpa',
        childIds: [],
        required: true,
        type: 'number',
        innerText: '',
    },
    13: {
        id: 13,
        name: 'firm',
        childIds: [],
        required: true,
        type: 'text',
        innerText: '',
    },
    14: {
        id: 14,
        name: 'years',
        childIds: [],
        required: true,
        type: 'number',
        innerText: '',
    },
    15: {
        id: 15,
        name: 'role',
        childIds: [],
        required: true,
        type: 'text',
        innerText: '',
    },

}

export default sections